### ISSUE TITLE
Attribution missing

### ISSUE THREAD

**Issue by samueldr** [lunik1/nixos-logo-gruvbox-wallpaper#1]
Hi!

As your README indicates:

> The NixOS logo is licensed under the Creative Commons Attribution 4.0 International License

It's missing the *attribution* required under the license. For the artwork repository we're [using this form](https://github.com/NixOS/nixos-artwork/tree/master/logo#credits)

> # Credits
>
> Logo designed by Tim Cuthbertson (@timbertson)

I guess an additional niceties would be to link to [the artwork repository](https://github.com/NixOS/nixos-artwork/tree/master/logo) in the formulation, which also gives the benefit of providing the upstream source for someone interested in further doing customizations.

Anyway, I hope I don't sound nagging. Licensing is hard, I'm not even *sure* this formulation is correct.

**Comment by lunik1** [comment]
Hi!

Thanks for brining this to my attention. You don't sound like a nag at all, attribution is important and I want to get it right 🙂 .

Could you the check the README in #2 and tell me if it is up to snuff?

**Comment by samueldr** [comment]
Looks about right!
