### ISSUE TITLE
Square variants?

### ISSUE THREAD

**Issue by colemickens** [lunik1/nixos-logo-gruvbox-wallpaper#3]
Hi!

I would love to use this wallpaper on my phone. Obviously I can crop it but I'm wondering if you were interested in facilitating versions where it's just the logo? Then I can stretch/tile/center it with `swaybg` for example?

Thank you! It's rare that I wind up on a wallpaper simple and elegant enough that it lasts more than a few hours, let a year+ at this point. Thank you for the art!

**Comment by lunik1** [comment]
Hello!

Thanks for the compliments. Did you have something like the below in mind? It's just a quick mock-up but I would be open to adding svg/png/webp versions corresponding to each wallapper.

![gruvbox-dark-rainbow-cropped](https://user-images.githubusercontent.com/13547699/162272727-b6591f7c-e4f0-4ffa-aaa0-60218bcbbc0c.png)

**Comment by colemickens** [comment]
Yes! Nothing too wild, and thanks for entertaining what amounts to a crop request. Single-source-of-truth guilt and all that. :)

**Comment by lunik1** [comment]
If you are happy with #4 I'll merge :)
